### ISSUE TITLE
Missing Card Background

### ISSUE THREAD

**Issue by Adam-Ant** [thomasloven/lovelace-time-input-row#2]
When used in 0.86.2, the card is missing background:
![190126-145159](https://user-images.githubusercontent.com/9141670/51788806-1b582900-217a-11e9-9d9a-299dd78d67eb.png)

Ui-Lovelace.yml extract:

```
resources:
  - url: /local/time-input-row.js
    type: js

[SNIP]

      - type: vertical-stack
        cards:
          - type: custom:time-input-row
            entity: input_datetime.alarm
          - type: glance
            entities:
              - entity: input_boolean.alarm_weekday
                tap_action:
                  action: toggle
              - entity: input_boolean.alarm_automated_on
                tap_action:
                  action: toggle
              - entity: input_boolean.alarm_auto_time
                tap_action:
                  action: toggle
```
